In [1]:
import numpy as np
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
type(iris)

sklearn.utils.Bunch

In [4]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [6]:
X = iris.data

In [7]:
X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [8]:
y = iris.target

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
# Performing one hot encoding on categorical targets
from tensorflow.keras.utils import to_categorical

y = to_categorical(y)
y.shape

(150, 3)

In [11]:
y[:15]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [13]:
# Scaling and standardizing data
from sklearn.preprocessing import MinMaxScaler

scaler_object = MinMaxScaler()
# Scaling it only on the train features to prevent the model from learning about the test features
scaler_object.fit(X_train)
scaled_X_train = scaler_object.transform(X_train)
scaled_X_test = scaler_object.transform(X_test)

In [14]:
scaled_X_train[:15]

array([[0.35294118, 0.18181818, 0.46428571, 0.375     ],
       [0.58823529, 0.36363636, 0.71428571, 0.58333333],
       [0.61764706, 0.5       , 0.78571429, 0.70833333],
       [0.67647059, 0.45454545, 0.58928571, 0.54166667],
       [0.85294118, 0.72727273, 0.89285714, 1.        ],
       [0.41176471, 0.40909091, 0.55357143, 0.5       ],
       [0.97058824, 0.45454545, 0.98214286, 0.83333333],
       [0.38235294, 0.45454545, 0.60714286, 0.58333333],
       [0.23529412, 0.68181818, 0.05357143, 0.04166667],
       [1.        , 0.36363636, 1.        , 0.79166667],
       [0.44117647, 0.31818182, 0.53571429, 0.375     ],
       [0.26470588, 0.63636364, 0.05357143, 0.04166667],
       [0.20588235, 0.68181818, 0.03571429, 0.08333333],
       [0.23529412, 0.81818182, 0.14285714, 0.125     ],
       [0.20588235, 0.        , 0.42857143, 0.375     ]])

In [15]:
scaled_X_test[:15]

array([[0.52941176, 0.36363636, 0.64285714, 0.45833333],
       [0.41176471, 0.81818182, 0.10714286, 0.08333333],
       [1.        , 0.27272727, 1.03571429, 0.91666667],
       [0.5       , 0.40909091, 0.60714286, 0.58333333],
       [0.73529412, 0.36363636, 0.66071429, 0.54166667],
       [0.32352941, 0.63636364, 0.07142857, 0.125     ],
       [0.38235294, 0.40909091, 0.44642857, 0.5       ],
       [0.76470588, 0.5       , 0.71428571, 0.91666667],
       [0.55882353, 0.09090909, 0.60714286, 0.58333333],
       [0.44117647, 0.31818182, 0.5       , 0.45833333],
       [0.64705882, 0.54545455, 0.71428571, 0.79166667],
       [0.14705882, 0.45454545, 0.05357143, 0.        ],
       [0.35294118, 0.68181818, 0.03571429, 0.04166667],
       [0.17647059, 0.5       , 0.07142857, 0.        ],
       [0.23529412, 0.81818182, 0.07142857, 0.08333333]])

In [16]:
# Building the network with Keras
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(8, input_dim = 4, activation = 'relu'))
model.add(Dense(8, input_dim = 4, activation = 'relu'))
# Use of softmax to get probablity of 3 classes in the output layer
model.add(Dense(3, activation = 'softmax')) 
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['accuracy'])

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [18]:
# Fit the model. We need note scale y_train since the output is already in 0's and 1's.
model.fit(scaled_X_train, y_train, epochs = 150, verbose = 2)

Epoch 1/150
4/4 - 0s - loss: 1.2012 - accuracy: 0.0000e+00 - 494ms/epoch - 123ms/step
Epoch 2/150
4/4 - 0s - loss: 1.1875 - accuracy: 0.0000e+00 - 8ms/epoch - 2ms/step
Epoch 3/150
4/4 - 0s - loss: 1.1758 - accuracy: 0.0000e+00 - 11ms/epoch - 3ms/step
Epoch 4/150
4/4 - 0s - loss: 1.1647 - accuracy: 0.0000e+00 - 10ms/epoch - 3ms/step
Epoch 5/150
4/4 - 0s - loss: 1.1538 - accuracy: 0.0476 - 9ms/epoch - 2ms/step
Epoch 6/150
4/4 - 0s - loss: 1.1437 - accuracy: 0.1238 - 9ms/epoch - 2ms/step
Epoch 7/150
4/4 - 0s - loss: 1.1342 - accuracy: 0.2190 - 16ms/epoch - 4ms/step
Epoch 8/150
4/4 - 0s - loss: 1.1253 - accuracy: 0.2667 - 8ms/epoch - 2ms/step
Epoch 9/150
4/4 - 0s - loss: 1.1167 - accuracy: 0.2857 - 8ms/epoch - 2ms/step
Epoch 10/150
4/4 - 0s - loss: 1.1091 - accuracy: 0.3143 - 8ms/epoch - 2ms/step
Epoch 11/150
4/4 - 0s - loss: 1.1024 - accuracy: 0.3333 - 7ms/epoch - 2ms/step
Epoch 12/150
4/4 - 0s - loss: 1.0955 - accuracy: 0.3524 - 8ms/epoch - 2ms/step
Epoch 13/150
4/4 - 0s - loss: 1.0895 -

In [19]:
np.argmax(model.predict(scaled_X_test), axis=-1)

array([1, 0, 2, 1, 2, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [20]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [21]:
# Converting the y_test into argmax form just like the predictions
predictions = np.argmax(model.predict(scaled_X_test), axis=-1)

In [22]:
y_test.argmax(axis = 1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [23]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

print(confusion_matrix(y_test.argmax(axis = 1), predictions))

[[19  0  0]
 [ 0 11  2]
 [ 0  0 13]]


In [24]:
print(classification_report(y_test.argmax(axis = 1), predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.85      0.92        13
           2       0.87      1.00      0.93        13

    accuracy                           0.96        45
   macro avg       0.96      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45



In [25]:
print(accuracy_score(y_test.argmax(axis = 1), predictions))

0.9555555555555556


In [26]:
# Saving the weights of the model
model.save('iris_classification_keras.h5')

In [27]:
from keras.models import load_model

new_model = load_model('iris_classification_keras.h5')
new_model.predict(scaled_X_test)[:15]

array([[2.6692435e-02, 6.1059690e-01, 3.6271062e-01],
       [9.3915576e-01, 5.8998633e-02, 1.8455421e-03],
       [5.2340041e-05, 1.1149048e-01, 8.8845712e-01],
       [1.7565824e-02, 5.6660467e-01, 4.1582951e-01],
       [6.7765559e-03, 4.8337361e-01, 5.0984985e-01],
       [9.1215879e-01, 8.4180512e-02, 3.6607974e-03],
       [8.7733522e-02, 6.7828357e-01, 2.3398286e-01],
       [4.6020307e-04, 2.2457099e-01, 7.7496880e-01],
       [3.9144345e-03, 3.3623967e-01, 6.5984595e-01],
       [5.5058163e-02, 6.5807569e-01, 2.8686613e-01],
       [2.4138426e-03, 3.7445489e-01, 6.2313128e-01],
       [9.2766535e-01, 6.8696044e-02, 3.6386077e-03],
       [9.4310802e-01, 5.4964080e-02, 1.9278615e-03],
       [9.3266219e-01, 6.4181216e-02, 3.1565458e-03],
       [9.5720917e-01, 4.1494835e-02, 1.2959557e-03]], dtype=float32)